### ISSUE TITLE
Bug reading missing binary operator

### ISSUE THREAD

**Issue by saona-raimundo** [bertiqwerty/exmex#2]
Hi there!

`exmex = { version: 0.7.1 }`

**Description**
Parsing the expression `2sin({x})` generates a panic, while an error is expected.

**Details**

Running the following code generates a panic, while it should be a parse error.

```rust
fn main() {
    let e = exmex::parse::<f64>("2sin({x})", &exmex::make_default_operators::<f64>());
    println!("{:?}", e);
}
```

This is the panic error I get `This is probably a bug. Expected binary operator but there was none.`

**Comment by bertiqwerty** [comment]
Thanks for your reports. I did not realize somebody else is using this and there were issues 😊. Good spot on this bug. There is a check missing.

**Comment by saona-raimundo** [comment]
Thank you!
