### ISSUE TITLE
Substitution of variables with expressions

### ISSUE THREAD

**Issue by shumpohl** [bertiqwerty/exmex#42]
It would be nice to be able to substitute variables with arbitrary expressions.

My current workaround is to unparse, use `regex` replacement functionality and re-parse the expression.

**Comment by bertiqwerty** [comment]
This is similar to #39. Can you give an example how you would want that to work syntactically as library user?

**Comment by shumpohl** [comment]
Let's the following method is added to `FlatEx`
```rust
/// EDITED: calls f with all variable names of self in the same order as self.var_names()
fn substituted<F>(&self, f: F) -> Self where F: FnMut(&str) -> Option<Self> {
    todo!()
}
```

```rust
let some_expr = FlatEx::from_str("x*3+y/z")?;

// some other place in code
let substitutions: HashSet = [("x", FlatEx::from_str("a+b")?), ("z", FlatEx::from_str("3.4")?)].into_iter().collect();

let new_expression = some_expr.substituted(|name| subtitutions.get(name));
assert_eq!("(a+b)*3+y/3.4", new_expression.unparse()?)
```

**Comment by bertiqwerty** [comment]
Are you missing to loop over the `HashSet`? Why does substituted have a callable as parameter instead of `substituted(&self, name: &str, expr: Self) -> Self`?

**Comment by shumpohl** [comment]
I added a docstring to clarify the behaviour. I wanted to choose the form that imposes the least in the user. You can use it with a correctly ordered list of substitutions or with an aribtrary map.

One key property is that the substitutions are done at the same time.
```
let expr = "x/y".parse()?;
let substituted = expr.substituted(|name| {
    match name {
        "x" => Some("y".parse().unwrap()),
        "y" => Some("x".parse().unwrap())
});
assert_eq!("y/x", substituted.unparse())
```

So in principle I want a rust equivalent to sympy's [`subs`](https://docs.sympy.org/latest/tutorials/intro-tutorial/basic_operations.html#substitution)

Alternatively maybe something like:
```rust
fn subs<R: IntoIterator<Item=(&str, FlatEx)>>(&self, replacements: R)  -> Result<Self> {
    todo!()
}
```

**Comment by bertiqwerty** [comment]
Ah. Yeah. That looks interesting. I will think about how to implement this.

**Comment by bertiqwerty** [comment]
Like so?
https://github.com/bertiqwerty/exmex/blob/7933e1a394884b22d11ff08a85248495c2516a3c/src/expression/deep.rs#L1147
