### ISSUE TITLE
More common math binary operators such as atan2

### ISSUE THREAD

**Issue by zopieux** [bertiqwerty/exmex#51]
exmex (partial) derivation feature is awesome but the lack of some common math/trigonometry binary operators reduces its general usefulness. It'd be awesome if operators like [`atan2`](https://docs.rs/num-dual/0.8.1/num_dual/struct.Dual.html#method.atan2) were implemented, including their derivatives.

**Comment by bertiqwerty** [comment]
What else except atan2 is missing?

**Comment by zopieux** [comment]
Actually it looks like it's pretty much the only binary one. On the unary side, perhaps the h variants of the various `a*h` like `atanh` etc. You can use that list as reference: https://docs.sympy.org/latest/modules/functions/elementary.html: it mentions atan2, asinh, etc.

**Comment by bertiqwerty** [comment]
What is you use case that you need functions like atanh or asinh?

**Comment by bertiqwerty** [comment]
`atan2` has been implemented in #52 with function call syntax `atan2(y, x)`.
