### ISSUE TITLE
Found multiple crashes using fuzzing

### ISSUE THREAD

**Issue by Nereuxofficial** [bertiqwerty/exmex#8]
I fuzzed this crate using honggfuzz and found 3 crashes.

You can fuzz the code yourself and further investigate the crashes with [this repo](https://github.com/Nereuxofficial/Fuzzing/tree/exmex).

In [the main function](https://github.com/Nereuxofficial/Fuzzing/blob/exmex/src/main.rs) there are also three test functions which can be used to easily reproduce the crashes. If you go into the [hfuzz_workspace/Fuzzing Folder](https://github.com/Nereuxofficial/Fuzzing/tree/exmex/hfuzz_workspace/Fuzzing) you can also see the inputs that crash.

This could help improve the check_preconditions function and i hope this is useful.

**Comment by bertiqwerty** [comment]
Thanks for report. Interesting. I haven't thought about using fuzzying yet. 

The strings reported are
- `(nc7)sqrtE`
- `fi.g`
- `xo-17-(((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((expWW-tr-3746-4+sinnex-nn--nnexpWW-tr-7492-4+4-nsqrnexq+---------282)-384`

**Comment by Nereuxofficial** [comment]
Through further fuzzing i found some more crashes.
Would it be okay if i forked the project and made a PR to have fuzzing built into the Project?

**Comment by bertiqwerty** [comment]
Do you mean a fuzzing test and an additional dev-dependency for the fuzzing lib?

**Comment by Nereuxofficial** [comment]
Yup. It would be in a fuzz/ folder similar to [this crate](https://github.com/tafia/quick-xml/tree/master/fuzz).
Note that it's not a dev-dependency and only compiled when someone actually wants to fuzz the crate

**Comment by bertiqwerty** [comment]
Yes, sure. Thanks.
